// manager/src/pages/DashboardPage.tsx
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import {
  Box,
  Typography,
  Paper,
  Card,
  CardContent,
  IconButton,
  ToggleButton,
  ToggleButtonGroup,
  Tooltip,
} from '@mui/material'
import Grid from '@mui/material/Grid2'
import RefreshIcon from '@mui/icons-material/Refresh'
import { dashboardApi } from '../api/dashboard'
import { useAuth } from '../contexts/AuthContext'
import ActivityChart from '../components/charts/ActivityChart'
import ProviderRankingChart from '../components/charts/ProviderRankingChart'
import MemberStatsTable from '../components/MemberStatsTable'

type TimeRange = '24h' | '7d' | '30d'

export default function DashboardPage() {
  const { isAdmin } = useAuth()
  const [timeRange, setTimeRange] = useState<TimeRange>('7d')

  const {
    data: metricsData,
    isLoading: metricsLoading,
    refetch: refetchMetrics,
  } = useQuery({
    queryKey: ['dashboard', 'metrics', timeRange],
    queryFn: () => dashboardApi.getMetrics(timeRange, 'hour'),
  })

  const {
    data: rankingsData,
    isLoading: rankingsLoading,
    refetch: refetchRankings,
  } = useQuery({
    queryKey: ['dashboard', 'rankings'],
    queryFn: () => dashboardApi.getRankings(),
  })

  const {
    data: membersData,
    isLoading: membersLoading,
    refetch: refetchMembers,
  } = useQuery({
    queryKey: ['dashboard', 'members'],
    queryFn: () => dashboardApi.getMembers(),
    enabled: isAdmin,
  })

  const handleRefresh = () => {
    refetchMetrics()
    refetchRankings()
    if (isAdmin) {
      refetchMembers()
    }
  }

  const handleTimeRangeChange = (_: React.MouseEvent<HTMLElement>, newRange: TimeRange | null) => {
    if (newRange) {
      setTimeRange(newRange)
    }
  }

  const summary = metricsData?.summary

  return (
    <Box>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Typography variant="h4">Dashboard</Typography>
        <Box sx={{ display: 'flex', gap: 2, alignItems: 'center' }}>
          <ToggleButtonGroup
            value={timeRange}
            exclusive
            onChange={handleTimeRangeChange}
            size="small"
          >
            <ToggleButton value="24h">24h</ToggleButton>
            <ToggleButton value="7d">7 Days</ToggleButton>
            <ToggleButton value="30d">30 Days</ToggleButton>
          </ToggleButtonGroup>
          <Tooltip title="Refresh data">
            <IconButton onClick={handleRefresh}>
              <RefreshIcon />
            </IconButton>
          </Tooltip>
        </Box>
      </Box>

      {/* Summary Cards */}
      <Grid container spacing={2} sx={{ mb: 3 }}>
        <Grid size={{ xs: 6, md: 3 }}>
          <Card>
            <CardContent>
              <Typography color="text.secondary" variant="body2">
                Total Requests
              </Typography>
              <Typography variant="h5">
                {summary?.total_requests?.toLocaleString() || '0'}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid size={{ xs: 6, md: 3 }}>
          <Card>
            <CardContent>
              <Typography color="text.secondary" variant="body2">
                Total Tokens
              </Typography>
              <Typography variant="h5">
                {summary?.total_tokens
                  ? summary.total_tokens >= 1000000
                    ? `${(summary.total_tokens / 1000000).toFixed(1)}M`
                    : summary.total_tokens >= 1000
                    ? `${(summary.total_tokens / 1000).toFixed(0)}K`
                    : summary.total_tokens
                  : '0'}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid size={{ xs: 6, md: 3 }}>
          <Card>
            <CardContent>
              <Typography color="text.secondary" variant="body2">
                AI Active Time
              </Typography>
              <Typography variant="h5">
                {summary?.total_active_time_hours
                  ? `${summary.total_active_time_hours.toFixed(1)}h`
                  : '0h'}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid size={{ xs: 6, md: 3 }}>
          <Card>
            <CardContent>
              <Typography color="text.secondary" variant="body2">
                Est. Cost
              </Typography>
              <Typography variant="h5">
                ${summary?.estimated_cost?.toFixed(2) || '0.00'}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      {/* Charts Row */}
      <Grid container spacing={3} sx={{ mb: 3 }}>
        <Grid size={{ xs: 12, md: 8 }}>
          <Paper sx={{ p: 3 }}>
            <ActivityChart
              data={metricsData?.data_points || []}
              isLoading={metricsLoading}
            />
          </Paper>
        </Grid>
        <Grid size={{ xs: 12, md: 4 }}>
          <Paper sx={{ p: 3, height: '100%' }}>
            <ProviderRankingChart
              rankings={rankingsData?.rankings || []}
              isLoading={rankingsLoading}
            />
          </Paper>
        </Grid>
      </Grid>

      {/* Member Stats Table (Admin only) */}
      {isAdmin && (
        <Paper sx={{ p: 3 }}>
          <MemberStatsTable
            members={membersData?.members || []}
            isLoading={membersLoading}
          />
        </Paper>
      )}
    </Box>
  )
}

// manager/src/pages/DashboardPage.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useAuthStore } from '../stores/auth'
import { dashboardApi } from '../api/dashboard'
import type { DashboardMetricsResponse, DashboardRankingsResponse, DashboardMembersResponse } from '../types/api'
import ActivityChart from '../components/charts/ActivityChart.vue'
import ProviderRankingChart from '../components/charts/ProviderRankingChart.vue'
import MemberStatsTable from '../components/charts/MemberStatsTable.vue'

const authStore = useAuthStore()

type TimeRange = '24h' | '7d' | '30d'
const timeRange = ref<TimeRange>('7d')

const metricsData = ref<DashboardMetricsResponse | null>(null)
const metricsLoading = ref(false)

const rankingsData = ref<DashboardRankingsResponse | null>(null)
const rankingsLoading = ref(false)

const membersData = ref<DashboardMembersResponse | null>(null)
const membersLoading = ref(false)

const summary = computed(() => metricsData.value?.summary)

async function fetchMetrics() {
  metricsLoading.value = true
  try {
    metricsData.value = await dashboardApi.getMetrics(timeRange.value, 'hour')
  } finally {
    metricsLoading.value = false
  }
}

async function fetchRankings() {
  rankingsLoading.value = true
  try {
    rankingsData.value = await dashboardApi.getRankings()
  } finally {
    rankingsLoading.value = false
  }
}

async function fetchMembers() {
  if (!authStore.isAdmin) return
  membersLoading.value = true
  try {
    membersData.value = await dashboardApi.getMembers()
  } finally {
    membersLoading.value = false
  }
}

function handleRefresh() {
  fetchMetrics()
  fetchRankings()
  if (authStore.isAdmin) {
    fetchMembers()
  }
}

function handleTimeRangeChange(newRange: TimeRange) {
  timeRange.value = newRange
  fetchMetrics()
}

function formatTokens(value: number): string {
  if (value >= 1000000) return `${(value / 1000000).toFixed(1)}M`
  if (value >= 1000) return `${(value / 1000).toFixed(0)}K`
  return value.toString()
}

onMounted(() => {
  fetchMetrics()
  fetchRankings()
  if (authStore.isAdmin) {
    fetchMembers()
  }
})
</script>

<template>
  <div>
    <div class="flex justify-between items-center mb-6">
      <h1 class="text-3xl font-bold">Dashboard</h1>
      <div class="flex gap-4 items-center">
        <div class="inline-flex rounded-md shadow-sm" role="group">
          <button
            v-for="range in ['24h', '7d', '30d'] as TimeRange[]"
            :key="range"
            @click="handleTimeRangeChange(range)"
            class="px-4 py-2 text-sm font-medium"
            :class="{
              'bg-blue-600 text-white': timeRange === range,
              'bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 border border-gray-300 dark:border-gray-600 hover:bg-gray-50 dark:hover:bg-gray-700': timeRange !== range
            }"
          >
            {{ range === '24h' ? '24h' : range === '7d' ? '7 Days' : '30 Days' }}
          </button>
        </div>
        <button
          @click="handleRefresh"
          class="p-2 rounded-full hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors"
          title="Refresh data"
        >
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
          </svg>
        </button>
      </div>
    </div>

    <!-- Summary Cards -->
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
      <div class="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
        <p class="text-sm text-gray-600 dark:text-gray-400">Total Requests</p>
        <p class="text-2xl font-bold">{{ summary?.total_requests?.toLocaleString() || '0' }}</p>
      </div>
      <div class="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
        <p class="text-sm text-gray-600 dark:text-gray-400">Total Tokens</p>
        <p class="text-2xl font-bold">{{ summary?.total_tokens ? formatTokens(summary.total_tokens) : '0' }}</p>
      </div>
      <div class="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
        <p class="text-sm text-gray-600 dark:text-gray-400">AI Active Time</p>
        <p class="text-2xl font-bold">{{ summary?.total_active_time_hours ? `${summary.total_active_time_hours.toFixed(1)}h` : '0h' }}</p>
      </div>
      <div class="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
        <p class="text-sm text-gray-600 dark:text-gray-400">Est. Cost</p>
        <p class="text-2xl font-bold">${{ summary?.estimated_cost?.toFixed(2) || '0.00' }}</p>
      </div>
    </div>

    <!-- Charts Row -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
      <div class="lg:col-span-2 bg-white dark:bg-gray-800 rounded-lg shadow p-6">
        <ActivityChart
          :data="metricsData?.data_points || []"
          :is-loading="metricsLoading"
        />
      </div>
      <div class="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
        <ProviderRankingChart
          :rankings="rankingsData?.rankings || []"
          :is-loading="rankingsLoading"
        />
      </div>
    </div>

    <!-- Member Stats Table (Admin only) -->
    <div v-if="authStore.isAdmin" class="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
      <MemberStatsTable
        :members="membersData?.members || []"
        :is-loading="membersLoading"
      />
    </div>
  </div>
</template>
