// manager/src/pages/TokenHistoryPage.tsx
import { useState } from 'react';
import { Box, Typography, Paper, Stack, Button, Alert } from '@mui/material';
import { DataGrid, GridColDef, GridPaginationModel, GridSortModel } from '@mui/x-data-grid';
import { useQuery } from '@tanstack/react-query';
import RefreshIcon from '@mui/icons-material/Refresh';
import DownloadIcon from '@mui/icons-material/Download';
import SearchIcon from '@mui/icons-material/Search';
import dayjs from 'dayjs';
import DateRangePicker from '../components/common/DateRangePicker';
import MultiSelect from '../components/common/MultiSelect';
import UserSelect from '../components/common/UserSelect';
import { analyticsApi } from '../api/analytics';

function formatNumber(num: number): string {
  if (num >= 1000000) return `${(num / 1000000).toFixed(1)}M`;
  if (num >= 1000) return `${(num / 1000).toFixed(1)}K`;
  return num.toString();
}

function formatDuration(ms: number): string {
  if (ms >= 1000) return `${(ms / 1000).toFixed(2)}s`;
  return `${ms}ms`;
}

export default function TokenHistoryPage() {
  const [startDate, setStartDate] = useState(dayjs().subtract(7, 'day').format('YYYY-MM-DD'));
  const [endDate, setEndDate] = useState(dayjs().format('YYYY-MM-DD'));
  const [selectedProviders, setSelectedProviders] = useState<string[]>([]);
  const [selectedModels, setSelectedModels] = useState<string[]>([]);
  const [selectedUsers, setSelectedUsers] = useState<number[]>([]);
  const [paginationModel, setPaginationModel] = useState<GridPaginationModel>({ page: 0, pageSize: 25 });
  const [sortModel, setSortModel] = useState<GridSortModel>([{ field: 'created_at', sort: 'desc' }]);

  // Search params (applied when Search is clicked)
  const [searchParams, setSearchParams] = useState({
    startDate: dayjs().subtract(7, 'day').format('YYYY-MM-DD'),
    endDate: dayjs().format('YYYY-MM-DD'),
    providers: [] as string[],
    models: [] as string[],
    userIds: [] as number[],
  });

  const { data: filterOptions, isLoading: filterLoading } = useQuery({
    queryKey: ['filterOptions'],
    queryFn: analyticsApi.getFilterOptions,
  });

  const { data, isLoading, error, refetch } = useQuery({
    queryKey: ['history', searchParams, paginationModel, sortModel],
    queryFn: () => analyticsApi.getHistory({
      start_date: searchParams.startDate,
      end_date: searchParams.endDate,
      page: paginationModel.page + 1,
      limit: paginationModel.pageSize,
      providers: searchParams.providers.length > 0 ? searchParams.providers : undefined,
      models: searchParams.models.length > 0 ? searchParams.models : undefined,
      user_ids: searchParams.userIds.length > 0 ? searchParams.userIds : undefined,
      sort_by: sortModel[0]?.field || 'created_at',
      sort_order: sortModel[0]?.sort || 'desc',
    }),
  });

  const handleDateChange = (start: string, end: string) => {
    setStartDate(start);
    setEndDate(end);
  };

  const handleSearch = () => {
    setPaginationModel({ ...paginationModel, page: 0 });
    setSearchParams({
      startDate,
      endDate,
      providers: selectedProviders,
      models: selectedModels,
      userIds: selectedUsers,
    });
  };

  const handleExportCSV = () => {
    if (!data) return;

    const headers = ['ID', 'User', 'Provider', 'Model', 'Input Tokens', 'Output Tokens', 'Duration', 'Created At'];
    const rows = data.records.map(r => [
      r.id,
      r.user_name,
      r.provider,
      r.model,
      r.input_tokens,
      r.output_tokens,
      r.duration_ms,
      r.created_at,
    ]);

    const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `token-history-${startDate}-${endDate}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const columns: GridColDef[] = [
    { field: 'id', headerName: 'ID', width: 80 },
    { field: 'user_name', headerName: 'User', flex: 1 },
    { field: 'provider', headerName: 'Provider', width: 120 },
    { field: 'model', headerName: 'Model', width: 200 },
    { field: 'input_tokens', headerName: 'Input', type: 'number', width: 100, valueFormatter: (value: number) => formatNumber(value) },
    { field: 'output_tokens', headerName: 'Output', type: 'number', width: 100, valueFormatter: (value: number) => formatNumber(value) },
    { field: 'duration_ms', headerName: 'Duration', type: 'number', width: 100, valueFormatter: (value: number) => formatDuration(value) },
    {
      field: 'created_at',
      headerName: 'Created At',
      width: 180,
      valueFormatter: (value: string) => dayjs(value).format('YYYY-MM-DD HH:mm:ss'),
    },
  ];

  if (error) {
    return (
      <Alert severity="error">
        Failed to load history. Please try again.
      </Alert>
    );
  }

  return (
    <Box>
      <Stack direction="row" justifyContent="space-between" alignItems="center" mb={3}>
        <Typography variant="h4">Token History</Typography>
        <Stack direction="row" spacing={1}>
          <Button startIcon={<RefreshIcon />} onClick={() => refetch()}>
            Refresh
          </Button>
          <Button startIcon={<DownloadIcon />} variant="outlined" onClick={handleExportCSV} disabled={!data}>
            Export CSV
          </Button>
        </Stack>
      </Stack>

      {/* Filters */}
      <Paper sx={{ p: 2, mb: 3 }}>
        <Stack direction="row" spacing={2} alignItems="center" flexWrap="wrap" useFlexGap>
          <DateRangePicker
            startDate={startDate}
            endDate={endDate}
            onChange={handleDateChange}
          />
          <UserSelect
            label="Users"
            options={filterOptions?.users || []}
            value={selectedUsers}
            onChange={setSelectedUsers}
          />
          <MultiSelect
            label="Providers"
            options={filterOptions?.providers || []}
            value={selectedProviders}
            onChange={setSelectedProviders}
          />
          <MultiSelect
            label="Models"
            options={filterOptions?.models || []}
            value={selectedModels}
            onChange={setSelectedModels}
          />
          <Button
            variant="contained"
            startIcon={<SearchIcon />}
            onClick={handleSearch}
            disabled={filterLoading}
          >
            Search
          </Button>
        </Stack>
      </Paper>

      {/* Data Table */}
      <Paper sx={{ p: 2 }}>
        <DataGrid
          rows={data?.records || []}
          columns={columns}
          loading={isLoading}
          rowCount={data?.pagination?.total || 0}
          paginationMode="server"
          paginationModel={paginationModel}
          onPaginationModelChange={setPaginationModel}
          sortingMode="server"
          sortModel={sortModel}
          onSortModelChange={setSortModel}
          pageSizeOptions={[10, 25, 50, 100]}
          autoHeight
          disableRowSelectionOnClick
          sx={{ minHeight: 400 }}
        />
      </Paper>
    </Box>
  );
}

// manager/src/pages/TokenHistoryPage.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import dayjs from 'dayjs'
import DateRangePicker from '../components/common/DateRangePicker.vue'
import MultiSelect from '../components/common/MultiSelect.vue'
import UserSelect from '../components/common/UserSelect.vue'
import { analyticsApi, type HistoryResponse, type FilterOptions } from '../api/analytics'

const startDate = ref(dayjs().subtract(7, 'day').format('YYYY-MM-DD'))
const endDate = ref(dayjs().format('YYYY-MM-DD'))
const selectedProviders = ref<string[]>([])
const selectedModels = ref<string[]>([])
const selectedUsers = ref<number[]>([])

const paginationModel = ref({ page: 0, pageSize: 25 })
const sortModel = ref({ field: 'created_at', order: 'desc' as 'asc' | 'desc' })

const searchParams = ref({
  startDate: dayjs().subtract(7, 'day').format('YYYY-MM-DD'),
  endDate: dayjs().format('YYYY-MM-DD'),
  providers: [] as string[],
  models: [] as string[],
  userIds: [] as number[],
})

const filterOptions = ref<FilterOptions | null>(null)
const data = ref<HistoryResponse | null>(null)
const isLoading = ref(false)
const filterLoading = ref(false)
const error = ref<string | null>(null)

function formatNumber(num: number): string {
  if (num >= 1000000) return `${(num / 1000000).toFixed(1)}M`
  if (num >= 1000) return `${(num / 1000).toFixed(1)}K`
  return num.toString()
}

function formatDuration(sec: number): string {
  if (sec >= 60) return `${(sec / 60).toFixed(1)}m`
  if (sec >= 1) return `${sec.toFixed(2)}s`
  return `${sec * 1000}ms`
}

async function fetchFilterOptions() {
  filterLoading.value = true
  try {
    filterOptions.value = await analyticsApi.getFilterOptions()
  } finally {
    filterLoading.value = false
  }
}

async function fetchData() {
  isLoading.value = true
  error.value = null
  try {
    data.value = await analyticsApi.getHistory({
      start_date: searchParams.value.startDate,
      end_date: searchParams.value.endDate,
      page: paginationModel.value.page + 1,
      limit: paginationModel.value.pageSize,
      providers: searchParams.value.providers.length > 0 ? searchParams.value.providers : undefined,
      models: searchParams.value.models.length > 0 ? searchParams.value.models : undefined,
      user_ids: searchParams.value.userIds.length > 0 ? searchParams.value.userIds : undefined,
      sort_by: sortModel.value.field,
      sort_order: sortModel.value.order,
    })
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to load history'
  } finally {
    isLoading.value = false
  }
}

function handleDateChange(start: string, end: string) {
  startDate.value = start
  endDate.value = end
}

function handleSearch() {
  paginationModel.value.page = 0
  searchParams.value = {
    startDate: startDate.value,
    endDate: endDate.value,
    providers: selectedProviders.value,
    models: selectedModels.value,
    userIds: selectedUsers.value,
  }
  fetchData()
}

function handleRefresh() {
  fetchData()
}

function handleSort(field: string) {
  if (sortModel.value.field === field) {
    sortModel.value.order = sortModel.value.order === 'asc' ? 'desc' : 'asc'
  } else {
    sortModel.value.field = field
    sortModel.value.order = 'desc'
  }
  fetchData()
}

function handlePageChange(newPage: number) {
  paginationModel.value.page = newPage
  fetchData()
}

function handlePageSizeChange(newSize: number) {
  paginationModel.value.pageSize = newSize
  paginationModel.value.page = 0
  fetchData()
}

function handleExportCSV() {
  if (!data.value) return

  const headers = ['ID', 'User', 'Provider', 'Model', 'Input Tokens', 'Output Tokens', 'Duration', 'Timestamp']
  const rows = data.value.records.map(r => [
    r.id,
    r.user_name,
    r.provider,
    r.model,
    r.input_tokens,
    r.output_tokens,
    r.duration_sec,
    r.timestamp
  ])

  const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n')
  const blob = new Blob([csv], { type: 'text/csv' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `token-history-${searchParams.value.startDate}-${searchParams.value.endDate}.csv`
  a.click()
  URL.revokeObjectURL(url)
}

onMounted(() => {
  fetchFilterOptions()
  fetchData()
})
</script>

<template>
  <div>
    <div class="flex justify-between items-center mb-6">
      <h1 class="text-3xl font-bold">Token History</h1>
      <div class="flex gap-2">
        <button
          @click="handleRefresh"
          class="px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
        >
          ⟳ Refresh
        </button>
        <button
          @click="handleExportCSV"
          :disabled="!data"
          class="px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          📥 Export CSV
        </button>
      </div>
    </div>

    <div
      v-if="error"
      class="mb-4 p-4 rounded-lg bg-red-100 dark:bg-red-900 text-red-700 dark:text-red-200"
    >
      {{ error }}
      <button @click="error = null" class="float-right text-current opacity-70 hover:opacity-100">×</button>
    </div>

    <!-- Filters -->
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow p-4 mb-6">
      <div class="flex flex-wrap gap-4 items-center">
        <DateRangePicker
          :start-date="startDate"
          :end-date="endDate"
          @change="handleDateChange"
        />
        <UserSelect
          label="Users"
          :options="filterOptions?.users || []"
          v-model="selectedUsers"
        />
        <MultiSelect
          label="Providers"
          :options="filterOptions?.providers || []"
          v-model="selectedProviders"
        />
        <MultiSelect
          label="Models"
          :options="filterOptions?.models || []"
          v-model="selectedModels"
        />
        <button
          @click="handleSearch"
          :disabled="filterLoading"
          class="bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 text-white font-medium py-2 px-4 rounded-md transition-colors"
        >
          🔍 Search
        </button>
      </div>
    </div>

    <!-- Data Table -->
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow overflow-hidden">
      <div class="overflow-x-auto">
        <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
          <thead class="bg-gray-50 dark:bg-gray-900">
            <tr>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">
                ID
              </th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">
                User
              </th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">
                Provider
              </th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">
                Model
              </th>
              <th
                @click="handleSort('input_tokens')"
                class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800"
              >
                Input
                <span v-if="sortModel.field === 'input_tokens'">{{ sortModel.order === 'asc' ? '↑' : '↓' }}</span>
              </th>
              <th
                @click="handleSort('output_tokens')"
                class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800"
              >
                Output
                <span v-if="sortModel.field === 'output_tokens'">{{ sortModel.order === 'asc' ? '↑' : '↓' }}</span>
              </th>
              <th
                @click="handleSort('duration_sec')"
                class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800"
              >
                Duration
                <span v-if="sortModel.field === 'duration_sec'">{{ sortModel.order === 'asc' ? '↑' : '↓' }}</span>
              </th>
              <th
                @click="handleSort('created_at')"
                class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800"
              >
                Created At
                <span v-if="sortModel.field === 'created_at'">{{ sortModel.order === 'asc' ? '↑' : '↓' }}</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
            <tr v-if="isLoading">
              <td colspan="8" class="px-6 py-20 text-center">
                <div class="animate-spin text-4xl inline-block">⟳</div>
              </td>
            </tr>
            <tr v-else-if="!data?.records || data.records.length === 0">
              <td colspan="8" class="px-6 py-20 text-center text-gray-500 dark:text-gray-400">
                No records found
              </td>
            </tr>
            <tr v-else v-for="record in data.records" :key="record.id">
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-gray-100">{{ record.id }}</td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-gray-100">{{ record.user_name }}</td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-gray-100">{{ record.provider }}</td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-gray-100">{{ record.model }}</td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-gray-100">{{ formatNumber(record.input_tokens) }}</td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-gray-100">{{ formatNumber(record.output_tokens) }}</td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-gray-100">{{ formatDuration(record.duration_sec) }}</td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-gray-100">{{ dayjs(record.timestamp).format('YYYY-MM-DD HH:mm:ss') }}</td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Pagination -->
      <div v-if="data?.pagination" class="bg-gray-50 dark:bg-gray-900 px-6 py-3 flex items-center justify-between border-t border-gray-200 dark:border-gray-700">
        <div class="text-sm text-gray-700 dark:text-gray-300">
          Showing {{ ((data.pagination.page - 1) * data.pagination.limit) + 1 }} to {{ Math.min(data.pagination.page * data.pagination.limit, data.pagination.total_count) }} of {{ data.pagination.total_count.toLocaleString() }} results
        </div>
        <div class="flex items-center gap-2">
          <select
            :value="paginationModel.pageSize"
            @change="handlePageSizeChange(parseInt(($event.target as HTMLSelectElement).value))"
            class="px-2 py-1 border border-gray-300 dark:border-gray-600 rounded text-sm dark:bg-gray-800 dark:text-white"
          >
            <option :value="10">10 per page</option>
            <option :value="25">25 per page</option>
            <option :value="50">50 per page</option>
            <option :value="100">100 per page</option>
          </select>
          <div class="flex gap-1">
            <button
              @click="handlePageChange(paginationModel.page - 1)"
              :disabled="paginationModel.page === 0"
              class="px-3 py-1 border border-gray-300 dark:border-gray-600 rounded hover:bg-gray-100 dark:hover:bg-gray-800 disabled:opacity-50 disabled:cursor-not-allowed dark:text-white"
            >
              Previous
            </button>
            <span class="px-3 py-1 text-gray-700 dark:text-gray-300">
              Page {{ paginationModel.page + 1 }} of {{ data.pagination.total_pages }}
            </span>
            <button
              @click="handlePageChange(paginationModel.page + 1)"
              :disabled="paginationModel.page >= data.pagination.total_pages - 1"
              class="px-3 py-1 border border-gray-300 dark:border-gray-600 rounded hover:bg-gray-100 dark:hover:bg-gray-800 disabled:opacity-50 disabled:cursor-not-allowed dark:text-white"
            >
              Next
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
