// manager/src/pages/TokenProviderPage.tsx
import { useState, useMemo } from 'react';
import { Box, Typography, Paper, Card, CardContent, Stack, Button, Alert, CircularProgress } from '@mui/material';
import Grid from '@mui/material/Grid2';
import { DataGrid, GridColDef } from '@mui/x-data-grid';
import { useQuery } from '@tanstack/react-query';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, Legend } from 'recharts';
import RefreshIcon from '@mui/icons-material/Refresh';
import DownloadIcon from '@mui/icons-material/Download';
import SearchIcon from '@mui/icons-material/Search';
import dayjs from 'dayjs';
import DateRangePicker from '../components/common/DateRangePicker';
import MultiSelect from '../components/common/MultiSelect';
import { analyticsApi } from '../api/analytics';

const COLORS = ['#0088FE', '#00C49F', '#FFBB28', '#FF8042', '#8884D8', '#82CA9D', '#FF6B6B', '#4ECDC4'];

function formatNumber(num: number): string {
  if (num >= 1000000) return `${(num / 1000000).toFixed(1)}M`;
  if (num >= 1000) return `${(num / 1000).toFixed(1)}K`;
  return num.toString();
}

function formatCost(cost: number): string {
  return `$${cost.toFixed(2)}`;
}

export default function TokenProviderPage() {
  const [startDate, setStartDate] = useState(dayjs().subtract(7, 'day').format('YYYY-MM-DD'));
  const [endDate, setEndDate] = useState(dayjs().format('YYYY-MM-DD'));
  const [selectedProviders, setSelectedProviders] = useState<string[]>([]);
  const [selectedModels, setSelectedModels] = useState<string[]>([]);

  // Search params (applied when Search is clicked)
  const [searchParams, setSearchParams] = useState({
    startDate: dayjs().subtract(7, 'day').format('YYYY-MM-DD'),
    endDate: dayjs().format('YYYY-MM-DD'),
    providers: [] as string[],
    models: [] as string[],
  });

  const { data: filterOptions, isLoading: filterLoading } = useQuery({
    queryKey: ['filterOptions'],
    queryFn: analyticsApi.getFilterOptions,
  });

  const { data, isLoading, error, refetch } = useQuery({
    queryKey: ['providerAnalytics', searchParams],
    queryFn: () => analyticsApi.getProviderAnalytics({
      start_date: searchParams.startDate,
      end_date: searchParams.endDate,
      providers: searchParams.providers.length > 0 ? searchParams.providers : undefined,
      models: searchParams.models.length > 0 ? searchParams.models : undefined,
    }),
  });

  const handleDateChange = (start: string, end: string) => {
    setStartDate(start);
    setEndDate(end);
  };

  const handleSearch = () => {
    setSearchParams({
      startDate,
      endDate,
      providers: selectedProviders,
      models: selectedModels,
    });
  };

  const handleExportCSV = () => {
    if (!data || !data.distribution.by_provider) return;

    const headers = ['Provider', 'Requests', 'Total Tokens', 'Cost', 'Percentage'];
    const rows = data.distribution.by_provider.map((p: { name: string; requests: number; tokens: number; cost: number; percentage: number }) => [
      p.name,
      p.requests,
      p.tokens,
      p.cost.toFixed(4),
      p.percentage.toFixed(2) + '%',
    ]);

    const csv = [headers.join(','), ...rows.map((r: (string | number)[]) => r.join(','))].join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `provider-analytics-${searchParams.startDate}-${searchParams.endDate}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Transform trend_data for the chart
  const trendChartData = useMemo(() => {
    if (!data?.trend_data) return [];

    return data.trend_data
      .map((item: { date: string; by_provider: Record<string, number> }) => {
        const totalTokens = Object.values(item.by_provider).reduce((sum: number, val: number) => sum + val, 0);
        return {
          date: item.date,
          tokens: totalTokens,
          ...item.by_provider,
        };
      })
      .sort((a: { date: string }, b: { date: string }) => a.date.localeCompare(b.date));
  }, [data?.trend_data]);

  // Get unique providers from trend data for stacked bar chart
  const trendProviders = useMemo(() => {
    if (!data?.trend_data) return [];
    const providers = new Set<string>();
    data.trend_data.forEach((item: { by_provider: Record<string, number> }) => {
      Object.keys(item.by_provider).forEach((p: string) => providers.add(p));
    });
    return Array.from(providers);
  }, [data?.trend_data]);

  const columns: GridColDef[] = [
    { field: 'name', headerName: 'Provider', flex: 1 },
    { field: 'requests', headerName: 'Requests', type: 'number', width: 120 },
    { field: 'tokens', headerName: 'Total Tokens', type: 'number', width: 140, valueFormatter: (value: number) => formatNumber(value) },
    { field: 'percentage', headerName: 'Share', type: 'number', width: 100, valueFormatter: (value: number) => `${value.toFixed(1)}%` },
    { field: 'cost', headerName: 'Cost', type: 'number', width: 120, valueFormatter: (value: number) => formatCost(value) },
  ];

  if (error) {
    return (
      <Alert severity="error">
        Failed to load provider analytics. Please try again.
      </Alert>
    );
  }

  return (
    <Box>
      <Stack direction="row" justifyContent="space-between" alignItems="center" mb={3}>
        <Typography variant="h4">Provider Analytics</Typography>
        <Stack direction="row" spacing={1}>
          <Button startIcon={<RefreshIcon />} onClick={() => refetch()}>
            Refresh
          </Button>
          <Button startIcon={<DownloadIcon />} variant="outlined" onClick={handleExportCSV} disabled={!data || !data.distribution.by_provider}>
            Export CSV
          </Button>
        </Stack>
      </Stack>

      {/* Filters */}
      <Paper sx={{ p: 2, mb: 3 }}>
        <Stack direction="row" spacing={2} alignItems="center" flexWrap="wrap" useFlexGap>
          <DateRangePicker
            startDate={startDate}
            endDate={endDate}
            onChange={handleDateChange}
          />
          <MultiSelect
            label="Providers"
            options={filterOptions?.providers || []}
            value={selectedProviders}
            onChange={setSelectedProviders}
          />
          <MultiSelect
            label="Models"
            options={filterOptions?.models || []}
            value={selectedModels}
            onChange={setSelectedModels}
          />
          <Button
            variant="contained"
            startIcon={<SearchIcon />}
            onClick={handleSearch}
            disabled={filterLoading}
          >
            Search
          </Button>
        </Stack>
      </Paper>

      {isLoading ? (
        <Box display="flex" justifyContent="center" alignItems="center" minHeight={400}>
          <CircularProgress />
        </Box>
      ) : (
        <>
          {/* Summary Cards */}
          {data && (
            <Grid container spacing={3} mb={3}>
              <Grid size={{ xs: 12, sm: 6, md: 3 }}>
                <Card>
                  <CardContent>
                    <Typography color="text.secondary" gutterBottom>Total Requests</Typography>
                    <Typography variant="h4">{formatNumber(data.summary.total_requests)}</Typography>
                  </CardContent>
                </Card>
              </Grid>
              <Grid size={{ xs: 12, sm: 6, md: 3 }}>
                <Card>
                  <CardContent>
                    <Typography color="text.secondary" gutterBottom>Total Tokens</Typography>
                    <Typography variant="h4">{formatNumber(data.summary.total_tokens)}</Typography>
                  </CardContent>
                </Card>
              </Grid>
              <Grid size={{ xs: 12, sm: 6, md: 3 }}>
                <Card>
                  <CardContent>
                    <Typography color="text.secondary" gutterBottom>Input / Output</Typography>
                    <Typography variant="h4">
                      {formatNumber(data.summary.total_input)} / {formatNumber(data.summary.total_output)}
                    </Typography>
                  </CardContent>
                </Card>
              </Grid>
              <Grid size={{ xs: 12, sm: 6, md: 3 }}>
                <Card>
                  <CardContent>
                    <Typography color="text.secondary" gutterBottom>Total Cost</Typography>
                    <Typography variant="h4">{formatCost(data.summary.total_cost)}</Typography>
                  </CardContent>
                </Card>
              </Grid>
            </Grid>
          )}

          {/* Charts */}
          {data && data.distribution.by_provider && data.distribution.by_provider.length > 0 ? (
            <Grid container spacing={3} mb={3}>
              {/* Daily Trend - Stacked Bar Chart by Provider */}
              <Grid size={{ xs: 12, md: 8 }}>
                <Paper sx={{ p: 2, height: 400 }}>
                  <Typography variant="h6" gutterBottom>Daily Token Usage by Provider</Typography>
                  <ResponsiveContainer width="100%" height={330}>
                    <BarChart data={trendChartData}>
                      <CartesianGrid strokeDasharray="3 3" />
                      <XAxis dataKey="date" tickFormatter={(v: string) => dayjs(v).format('MM/DD')} />
                      <YAxis tickFormatter={formatNumber} />
                      <Tooltip
                        formatter={(value: number) => formatNumber(value)}
                        labelFormatter={(label: string) => dayjs(label).format('YYYY-MM-DD')}
                      />
                      <Legend />
                      {trendProviders.map((provider: string, index: number) => (
                        <Bar
                          key={provider}
                          dataKey={provider}
                          stackId="a"
                          fill={COLORS[index % COLORS.length]}
                          name={provider}
                        />
                      ))}
                    </BarChart>
                  </ResponsiveContainer>
                </Paper>
              </Grid>

              {/* Provider Distribution */}
              <Grid size={{ xs: 12, md: 4 }}>
                <Paper sx={{ p: 2, height: 400 }}>
                  <Typography variant="h6" gutterBottom>Provider Distribution</Typography>
                  <ResponsiveContainer width="100%" height={330}>
                    <PieChart>
                      <Pie
                        data={data.distribution.by_provider}
                        dataKey="tokens"
                        nameKey="name"
                        cx="50%"
                        cy="50%"
                        outerRadius={100}
                        label={({ name, percentage }: { name: string; percentage: number }) => `${name} ${percentage.toFixed(0)}%`}
                        labelLine={false}
                      >
                        {data.distribution.by_provider.map((_: unknown, index: number) => (
                          <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                        ))}
                      </Pie>
                      <Tooltip formatter={(value: number) => formatNumber(value)} />
                    </PieChart>
                  </ResponsiveContainer>
                </Paper>
              </Grid>
            </Grid>
          ) : data ? (
            <Alert severity="info" sx={{ mb: 3 }}>
              No usage data available for the selected time period. Start using AI providers to see analytics here.
            </Alert>
          ) : null}

          {/* Data Table */}
          {data && data.distribution.by_provider && data.distribution.by_provider.length > 0 && (
            <Paper sx={{ p: 2 }}>
              <Typography variant="h6" gutterBottom>Provider Details</Typography>
              <DataGrid
                rows={data.distribution.by_provider.map((p: { name: string; requests: number; tokens: number; cost: number; percentage: number }, i: number) => ({ id: i, ...p }))}
                columns={columns}
                autoHeight
                pageSizeOptions={[5, 10, 25]}
                initialState={{
                  pagination: { paginationModel: { pageSize: 10 } },
                }}
                disableRowSelectionOnClick
              />
            </Paper>
          )}
        </>
      )}
    </Box>
  );
}

// manager/src/pages/TokenProviderPage.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import dayjs from 'dayjs'
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  ArcElement,
  Title,
  Tooltip,
  Legend
} from 'chart.js'
import { Bar, Pie } from 'vue-chartjs'
import DateRangePicker from '../components/common/DateRangePicker.vue'
import MultiSelect from '../components/common/MultiSelect.vue'
import { analyticsApi, type ProviderAnalyticsResponse, type FilterOptions } from '../api/analytics'
import { exportCSV, exportJSON } from '../utils/export'

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  ArcElement,
  Title,
  Tooltip,
  Legend
)

const COLORS = ['#0088FE', '#00C49F', '#FFBB28', '#FF8042', '#8884D8', '#82CA9D', '#FF6B6B', '#4ECDC4']

const startDate = ref(dayjs().subtract(7, 'day').format('YYYY-MM-DD'))
const endDate = ref(dayjs().format('YYYY-MM-DD'))
const selectedProviders = ref<string[]>([])
const selectedModels = ref<string[]>([])

const searchParams = ref({
  startDate: dayjs().subtract(7, 'day').format('YYYY-MM-DD'),
  endDate: dayjs().format('YYYY-MM-DD'),
  providers: [] as string[],
  models: [] as string[],
})

const filterOptions = ref<FilterOptions | null>(null)
const data = ref<ProviderAnalyticsResponse | null>(null)
const isLoading = ref(false)
const filterLoading = ref(false)
const error = ref<string | null>(null)
const showExportMenu = ref(false)

function formatNumber(num: number): string {
  if (num >= 1000000) return `${(num / 1000000).toFixed(1)}M`
  if (num >= 1000) return `${(num / 1000).toFixed(1)}K`
  return num.toString()
}

function formatCost(cost: number): string {
  return `$${cost.toFixed(2)}`
}

async function fetchFilterOptions() {
  filterLoading.value = true
  try {
    filterOptions.value = await analyticsApi.getFilterOptions()
  } finally {
    filterLoading.value = false
  }
}

async function fetchData() {
  isLoading.value = true
  error.value = null
  try {
    data.value = await analyticsApi.getProviderAnalytics({
      start_date: searchParams.value.startDate,
      end_date: searchParams.value.endDate,
      providers: searchParams.value.providers.length > 0 ? searchParams.value.providers : undefined,
      models: searchParams.value.models.length > 0 ? searchParams.value.models : undefined,
    })
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to load provider analytics'
  } finally {
    isLoading.value = false
  }
}

function handleDateChange(start: string, end: string) {
  startDate.value = start
  endDate.value = end
}

function handleSearch() {
  searchParams.value = {
    startDate: startDate.value,
    endDate: endDate.value,
    providers: selectedProviders.value,
    models: selectedModels.value,
  }
  fetchData()
}

function handleRefresh() {
  fetchData()
}

function handleExportCSV() {
  if (!data.value?.distribution.by_provider) return

  const headers = ['Provider', 'Requests', 'Total Tokens', 'Cost', 'Percentage']
  const rows = data.value.distribution.by_provider.map(p => [
    p.name,
    p.requests,
    p.tokens,
    p.cost.toFixed(4),
    `${p.percentage.toFixed(2)}%`
  ])

  exportCSV(headers, rows, `provider-analytics-${searchParams.value.startDate}-${searchParams.value.endDate}`)
}

function handleExportJSON() {
  if (!data.value) return

  exportJSON(data.value.distribution.by_provider, `provider-analytics-${searchParams.value.startDate}-${searchParams.value.endDate}`)
}

// Chart data
const trendChartData = computed(() => {
  if (!data.value?.trend_data) return { labels: [], datasets: [] }

  const labels = data.value.trend_data.map(item => dayjs(item.date).format('MM/DD'))
  const providers = new Set<string>()
  data.value.trend_data.forEach(item => {
    Object.keys(item.by_provider).forEach(p => providers.add(p))
  })

  const datasets = Array.from(providers).map((provider, idx) => ({
    label: provider,
    data: data.value!.trend_data!.map(item => item.by_provider[provider] || 0),
    backgroundColor: COLORS[idx % COLORS.length],
    stack: 'Stack 0'
  }))

  return { labels, datasets }
})

const pieChartData = computed(() => {
  if (!data.value?.distribution.by_provider) return { labels: [], datasets: [] }
  return {
    labels: data.value.distribution.by_provider.map(p => p.name),
    datasets: [{
      data: data.value.distribution.by_provider.map(p => p.tokens),
      backgroundColor: COLORS.slice(0, data.value.distribution.by_provider.length)
    }]
  }
})

const barOptions = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: { position: 'top' as const }
  },
  scales: {
    x: { stacked: true },
    y: { stacked: true }
  }
}

const pieOptions = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: { display: false }
  }
}

onMounted(() => {
  fetchFilterOptions()
  fetchData()
})
</script>

<template>
  <div>
    <div class="flex justify-between items-center mb-6">
      <h1 class="text-3xl font-bold">Provider Analytics</h1>
      <div class="flex gap-2">
        <button
          @click="handleRefresh"
          class="px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
        >
          ⟳ Refresh
        </button>
        <div class="relative">
          <button
            @click="showExportMenu = !showExportMenu"
            :disabled="!data || !data.distribution.by_provider"
            class="px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            📥 Export ▼
          </button>
          <div
            v-if="showExportMenu"
            class="absolute right-0 mt-1 w-40 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-md shadow-lg z-10"
          >
            <button
              @click="handleExportCSV(); showExportMenu = false"
              class="w-full text-left px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-700"
            >
              CSV
            </button>
            <button
              @click="handleExportJSON(); showExportMenu = false"
              class="w-full text-left px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-700"
            >
              JSON
            </button>
          </div>
        </div>
      </div>
    </div>

    <div
      v-if="error"
      class="mb-4 p-4 rounded-lg bg-red-100 dark:bg-red-900 text-red-700 dark:text-red-200"
    >
      {{ error }}
      <button @click="error = null" class="float-right text-current opacity-70 hover:opacity-100">×</button>
    </div>

    <!-- Filters -->
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow p-4 mb-6">
      <div class="flex flex-wrap gap-4 items-center">
        <DateRangePicker
          :start-date="startDate"
          :end-date="endDate"
          @change="handleDateChange"
        />
        <MultiSelect
          label="Providers"
          :options="filterOptions?.providers || []"
          v-model="selectedProviders"
        />
        <MultiSelect
          label="Models"
          :options="filterOptions?.models || []"
          v-model="selectedModels"
        />
        <button
          @click="handleSearch"
          :disabled="filterLoading"
          class="bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 text-white font-medium py-2 px-4 rounded-md transition-colors"
        >
          🔍 Search
        </button>
      </div>
    </div>

    <div v-if="isLoading" class="flex justify-center items-center py-20">
      <div class="animate-spin text-4xl">⟳</div>
    </div>

    <div v-else-if="data">
      <!-- Summary Cards -->
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        <div class="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
          <p class="text-sm text-gray-600 dark:text-gray-400">Total Requests</p>
          <p class="text-2xl font-bold">{{ formatNumber(data.summary.total_requests) }}</p>
        </div>
        <div class="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
          <p class="text-sm text-gray-600 dark:text-gray-400">Total Tokens</p>
          <p class="text-2xl font-bold">{{ formatNumber(data.summary.total_tokens) }}</p>
        </div>
        <div class="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
          <p class="text-sm text-gray-600 dark:text-gray-400">Input / Output</p>
          <p class="text-2xl font-bold">{{ formatNumber(data.summary.total_input) }} / {{ formatNumber(data.summary.total_output) }}</p>
        </div>
        <div class="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
          <p class="text-sm text-gray-600 dark:text-gray-400">Total Cost</p>
          <p class="text-2xl font-bold">{{ formatCost(data.summary.total_cost) }}</p>
        </div>
      </div>

      <!-- Charts -->
      <div v-if="data.distribution.by_provider && data.distribution.by_provider.length > 0" class="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
        <!-- Daily Trend Chart -->
        <div class="lg:col-span-2 bg-white dark:bg-gray-800 rounded-lg shadow p-4">
          <h3 class="text-lg font-semibold mb-4">Daily Token Usage by Provider</h3>
          <div class="h-[330px]">
            <Bar :data="trendChartData" :options="barOptions" />
          </div>
        </div>

        <!-- Provider Distribution Pie Chart -->
        <div class="bg-white dark:bg-gray-800 rounded-lg shadow p-4">
          <h3 class="text-lg font-semibold mb-4">Provider Distribution</h3>
          <div class="h-[330px]">
            <Pie :data="pieChartData" :options="pieOptions" />
          </div>
        </div>
      </div>

      <div v-else class="mb-6 p-4 bg-blue-50 dark:bg-blue-900 text-blue-700 dark:text-blue-200 rounded-lg">
        No usage data available for the selected time period. Start using AI providers to see analytics here.
      </div>

      <!-- Provider Details Table -->
      <div v-if="data.distribution.by_provider && data.distribution.by_provider.length > 0" class="bg-white dark:bg-gray-800 rounded-lg shadow p-4">
        <h3 class="text-lg font-semibold mb-4">Provider Details</h3>
        <div class="overflow-x-auto">
          <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
            <thead class="bg-gray-50 dark:bg-gray-900">
              <tr>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">Provider</th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">Requests</th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">Total Tokens</th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">Share</th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">Cost</th>
              </tr>
            </thead>
            <tbody class="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
              <tr v-for="provider in data.distribution.by_provider" :key="provider.name">
                <td class="px-6 py-4 text-sm font-medium text-gray-900 dark:text-gray-100">{{ provider.name }}</td>
                <td class="px-6 py-4 text-sm text-gray-900 dark:text-gray-100">{{ provider.requests.toLocaleString() }}</td>
                <td class="px-6 py-4 text-sm text-gray-900 dark:text-gray-100">{{ formatNumber(provider.tokens) }}</td>
                <td class="px-6 py-4 text-sm text-gray-900 dark:text-gray-100">{{ provider.percentage.toFixed(1) }}%</td>
                <td class="px-6 py-4 text-sm text-gray-900 dark:text-gray-100">{{ formatCost(provider.cost) }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</template>
