// manager/src/components/layout/AppLayout.tsx
import { useState, useCallback, useEffect } from 'react'
import { Outlet } from 'react-router-dom'
import { Box, Drawer, Toolbar } from '@mui/material'
import Header from './Header'
import Sidebar from './Sidebar'

const MIN_DRAWER_WIDTH = 180
const MAX_DRAWER_WIDTH = 400
const DEFAULT_DRAWER_WIDTH = 240

export default function AppLayout() {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [drawerWidth, setDrawerWidth] = useState(() => {
    const saved = localStorage.getItem('sidebarWidth')
    return saved ? parseInt(saved, 10) : DEFAULT_DRAWER_WIDTH
  })
  const [isResizing, setIsResizing] = useState(false)

  const handleDrawerToggle = () => {
    setMobileOpen(!mobileOpen)
  }

  const handleMouseDown = useCallback((e: React.MouseEvent) => {
    e.preventDefault()
    setIsResizing(true)
  }, [])

  const handleMouseMove = useCallback(
    (e: MouseEvent) => {
      if (!isResizing) return

      const newWidth = e.clientX
      if (newWidth >= MIN_DRAWER_WIDTH && newWidth <= MAX_DRAWER_WIDTH) {
        setDrawerWidth(newWidth)
      }
    },
    [isResizing]
  )

  const handleMouseUp = useCallback(() => {
    if (isResizing) {
      setIsResizing(false)
      localStorage.setItem('sidebarWidth', drawerWidth.toString())
    }
  }, [isResizing, drawerWidth])

  useEffect(() => {
    if (isResizing) {
      document.addEventListener('mousemove', handleMouseMove)
      document.addEventListener('mouseup', handleMouseUp)
      document.body.style.cursor = 'col-resize'
      document.body.style.userSelect = 'none'
    }

    return () => {
      document.removeEventListener('mousemove', handleMouseMove)
      document.removeEventListener('mouseup', handleMouseUp)
      document.body.style.cursor = ''
      document.body.style.userSelect = ''
    }
  }, [isResizing, handleMouseMove, handleMouseUp])

  return (
    <Box sx={{ display: 'flex', minHeight: '100vh' }}>
      <Header onMenuClick={handleDrawerToggle} />

      {/* Mobile drawer */}
      <Drawer
        variant="temporary"
        open={mobileOpen}
        onClose={handleDrawerToggle}
        ModalProps={{ keepMounted: true }}
        sx={{
          display: { xs: 'block', sm: 'none' },
          '& .MuiDrawer-paper': {
            boxSizing: 'border-box',
            width: drawerWidth,
          },
        }}
      >
        <Sidebar />
      </Drawer>

      {/* Desktop drawer */}
      <Box
        component="nav"
        sx={{
          width: { sm: drawerWidth },
          flexShrink: { sm: 0 },
          display: { xs: 'none', sm: 'block' },
        }}
      >
        <Box
          sx={{
            width: drawerWidth,
            height: '100vh',
            position: 'fixed',
            top: 0,
            left: 0,
            bgcolor: 'background.paper',
            borderRight: 1,
            borderColor: 'divider',
            display: 'flex',
          }}
        >
          <Box sx={{ flexGrow: 1, overflow: 'hidden' }}>
            <Sidebar />
          </Box>

          {/* Resize handle */}
          <Box
            onMouseDown={handleMouseDown}
            sx={{
              width: 4,
              cursor: 'col-resize',
              bgcolor: isResizing ? 'primary.main' : 'transparent',
              transition: 'background-color 0.2s',
              '&:hover': {
                bgcolor: 'primary.light',
              },
            }}
          />
        </Box>
      </Box>

      {/* Main content */}
      <Box
        component="main"
        sx={{
          flexGrow: 1,
          p: 3,
          width: { sm: `calc(100% - ${drawerWidth}px)` },
          bgcolor: 'background.default',
          minHeight: '100vh',
        }}
      >
        <Toolbar />
        <Outlet />
      </Box>
    </Box>
  )
}

// manager/src/components/layout/AppLayout.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import Header from './Header.vue'
import Sidebar from './Sidebar.vue'

const MIN_DRAWER_WIDTH = 180
const MAX_DRAWER_WIDTH = 400
const DEFAULT_DRAWER_WIDTH = 240

const mobileOpen = ref(false)
const drawerWidth = ref(DEFAULT_DRAWER_WIDTH)
const isResizing = ref(false)

// Initialize drawer width from localStorage
const savedWidth = localStorage.getItem('sidebarWidth')
if (savedWidth) {
  drawerWidth.value = parseInt(savedWidth, 10)
}

function handleDrawerToggle() {
  mobileOpen.value = !mobileOpen.value
}

function handleMouseDown(e: MouseEvent) {
  e.preventDefault()
  isResizing.value = true
}

function handleMouseMove(e: MouseEvent) {
  if (!isResizing.value) return

  const newWidth = e.clientX
  if (newWidth >= MIN_DRAWER_WIDTH && newWidth <= MAX_DRAWER_WIDTH) {
    drawerWidth.value = newWidth
  }
}

function handleMouseUp() {
  if (isResizing.value) {
    isResizing.value = false
    localStorage.setItem('sidebarWidth', drawerWidth.value.toString())
  }
}

onMounted(() => {
  document.addEventListener('mousemove', handleMouseMove)
  document.addEventListener('mouseup', handleMouseUp)
})

onUnmounted(() => {
  document.removeEventListener('mousemove', handleMouseMove)
  document.removeEventListener('mouseup', handleMouseUp)
})
</script>

<template>
  <div class="flex min-h-screen bg-gray-50 dark:bg-gray-900">
    <Header @menu-click="handleDrawerToggle" />

    <!-- Mobile drawer -->
    <div
      v-if="mobileOpen"
      class="fixed inset-0 z-40 sm:hidden"
    >
      <div class="absolute inset-0 bg-black/50" @click="handleDrawerToggle"></div>
      <div
        class="absolute left-0 top-0 bottom-0 w-64 bg-white dark:bg-gray-800 shadow-lg"
        :style="{ width: `${drawerWidth}px` }"
      >
        <Sidebar />
      </div>
    </div>

    <!-- Desktop drawer -->
    <aside
      class="hidden sm:flex bg-white dark:bg-gray-800 border-r border-gray-200 dark:border-gray-700 flex-shrink-0"
      :style="{ width: `${drawerWidth}px` }"
    >
      <div class="flex-1 overflow-hidden">
        <Sidebar />
      </div>

      <!-- Resize handle -->
      <div
        @mousedown="handleMouseDown"
        class="w-1 cursor-col-resize hover:bg-blue-500 transition-colors"
        :class="{ 'bg-blue-500': isResizing }"
      ></div>
    </aside>

    <!-- Main content -->
    <main
      class="flex-1 p-6 bg-gray-50 dark:bg-gray-900 min-h-screen"
      :style="{ width: `calc(100% - ${drawerWidth}px)` }"
      :class="{ 'sm:ml-0': mobileOpen, 'sm:hidden': mobileOpen }"
    >
      <!-- Spacer for fixed header -->
      <div class="h-16"></div>
      <RouterView />
    </main>
  </div>
</template>
