// manager/src/components/charts/ActivityChart.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  Filler
} from 'chart.js'
import { Line } from 'vue-chartjs'
import type { MetricDataPoint } from '../../types/api'

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  Filler
)

interface Props {
  data: MetricDataPoint[]
  isLoading?: boolean
}

type ChartView = 'active_time' | 'tokens'

const props = defineProps<Props>()
const view = ref<ChartView>('active_time')

const chartData = computed(() => {
  return props.data.map(point => ({
    timestamp: new Date(point.timestamp).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric'
    }),
    fullDate: new Date(point.timestamp).toLocaleString(),
    activeTimeHours: point.active_time_seconds / 3600,
    totalTokens: point.total_tokens,
    inputTokens: point.input_tokens,
    outputTokens: point.output_tokens,
    requestCount: point.request_count
  }))
})

const activeTimeChartData = computed(() => ({
  labels: chartData.value.map(d => d.timestamp),
  datasets: [{
    label: 'AI Active Time (hours)',
    data: chartData.value.map(d => d.activeTimeHours),
    borderColor: '#1976d2',
    backgroundColor: 'rgba(25, 118, 210, 0.1)',
    tension: 0.4,
    fill: true
  }]
}))

const tokensChartData = computed(() => ({
  labels: chartData.value.map(d => d.timestamp),
  datasets: [
    {
      label: 'Input Tokens',
      data: chartData.value.map(d => d.inputTokens),
      borderColor: '#2196f3',
      backgroundColor: 'rgba(33, 150, 243, 0.1)',
      tension: 0.4
    },
    {
      label: 'Output Tokens',
      data: chartData.value.map(d => d.outputTokens),
      borderColor: '#4caf50',
      backgroundColor: 'rgba(76, 175, 80, 0.1)',
      tension: 0.4
    }
  ]
}))

const chartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: {
      display: true
    },
    tooltip: {
      mode: 'index' as const,
      intersect: false
    }
  },
  scales: {
    y: {
      beginAtZero: true
    }
  }
}

function handleViewChange(newView: ChartView) {
  view.value = newView
}
</script>

<template>
  <div>
    <div class="flex justify-between items-center mb-4">
      <h3 class="text-lg font-semibold">
        {{ view === 'active_time' ? 'AI Active Time' : 'Token Volume' }}
      </h3>
      <div class="flex rounded-md shadow-sm">
        <button
          @click="handleViewChange('active_time')"
          class="px-3 py-1 text-sm font-medium rounded-l-md"
          :class="{
            'bg-blue-600 text-white': view === 'active_time',
            'bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300': view !== 'active_time'
          }"
        >
          Active Time
        </button>
        <button
          @click="handleViewChange('tokens')"
          class="px-3 py-1 text-sm font-medium rounded-r-md"
          :class="{
            'bg-blue-600 text-white': view === 'tokens',
            'bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300': view !== 'tokens'
          }"
        >
          Tokens
        </button>
      </div>
    </div>

    <div v-if="isLoading" class="h-[300px] flex items-center justify-center">
      <p class="text-gray-500 dark:text-gray-400">Loading...</p>
    </div>

    <div v-else-if="data.length === 0" class="h-[300px] flex items-center justify-center">
      <p class="text-gray-500 dark:text-gray-400">No data available</p>
    </div>

    <div v-else class="h-[250px]">
      <Line
        v-if="view === 'active_time'"
        :data="activeTimeChartData"
        :options="chartOptions"
      />
      <Line
        v-else
        :data="tokensChartData"
        :options="chartOptions"
      />
    </div>
  </div>
</template>

// manager/src/components/charts/ActivityChart.tsx
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend,
} from 'recharts'
import { Box, ToggleButton, ToggleButtonGroup, Typography } from '@mui/material'
import { useState } from 'react'
import type { MetricDataPoint } from '../../types/api'

interface ActivityChartProps {
  data: MetricDataPoint[]
  isLoading?: boolean
}

type ChartView = 'active_time' | 'tokens'

export default function ActivityChart({ data, isLoading }: ActivityChartProps) {
  const [view, setView] = useState<ChartView>('active_time')

  const handleViewChange = (_: React.MouseEvent<HTMLElement>, newView: ChartView | null) => {
    if (newView) {
      setView(newView)
    }
  }

  // Format data for the chart
  const chartData = data.map((point) => ({
    timestamp: new Date(point.timestamp).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
    }),
    fullDate: new Date(point.timestamp).toLocaleString(),
    activeTimeHours: point.active_time_seconds / 3600,
    totalTokens: point.total_tokens,
    inputTokens: point.input_tokens,
    outputTokens: point.output_tokens,
    requestCount: point.request_count,
  }))

  if (isLoading) {
    return (
      <Box sx={{ height: 300, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <Typography color="text.secondary">Loading...</Typography>
      </Box>
    )
  }

  if (data.length === 0) {
    return (
      <Box sx={{ height: 300, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <Typography color="text.secondary">No data available</Typography>
      </Box>
    )
  }

  return (
    <Box>
      <Box sx={{ mb: 2, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Typography variant="h6">
          {view === 'active_time' ? 'AI Active Time' : 'Token Volume'}
        </Typography>
        <ToggleButtonGroup
          value={view}
          exclusive
          onChange={handleViewChange}
          size="small"
        >
          <ToggleButton value="active_time">Active Time</ToggleButton>
          <ToggleButton value="tokens">Tokens</ToggleButton>
        </ToggleButtonGroup>
      </Box>

      <ResponsiveContainer width="100%" height={250}>
        {view === 'active_time' ? (
          <LineChart data={chartData}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="timestamp" fontSize={12} />
            <YAxis
              fontSize={12}
              tickFormatter={(value) => `${value.toFixed(1)}h`}
            />
            <Tooltip
              formatter={(value: number) => [`${value.toFixed(2)} hours`, 'Active Time']}
            />
            <Legend />
            <Line
              type="monotone"
              dataKey="activeTimeHours"
              name="AI Active Time"
              stroke="#1976d2"
              strokeWidth={2}
              dot={{ r: 3 }}
              activeDot={{ r: 5 }}
            />
          </LineChart>
        ) : (
          <LineChart data={chartData}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="timestamp" fontSize={12} />
            <YAxis
              fontSize={12}
              tickFormatter={(value) => {
                if (value >= 1000000) return `${(value / 1000000).toFixed(1)}M`
                if (value >= 1000) return `${(value / 1000).toFixed(0)}K`
                return value.toString()
              }}
            />
            <Tooltip
              formatter={(value: number) => [value.toLocaleString(), 'Tokens']}
            />
            <Legend />
            <Line
              type="monotone"
              dataKey="inputTokens"
              name="Input Tokens"
              stroke="#2196f3"
              strokeWidth={2}
              dot={{ r: 2 }}
            />
            <Line
              type="monotone"
              dataKey="outputTokens"
              name="Output Tokens"
              stroke="#4caf50"
              strokeWidth={2}
              dot={{ r: 2 }}
            />
          </LineChart>
        )}
      </ResponsiveContainer>
    </Box>
  )
}
